# config_consts.py

DEBUG_OUTPUT = False
MACROPAD_DISPLAY_METERS = True

MACROPAD_BRIGHTNESS = 0.15
MACROPAD_SLEEP_KEYS = 60.0

MACROPAD_DISPLAY_FPS = 30.0

DISPLAY_METER_COUNT = 14
DISPLAY_METER_SPACING = 2

DISPLAY_METER_WIDTH = 10
DISPLAY_METER_HEIGHT = 40