# config_consts.py

DEBUG_OUTPUT = False
MACROPAD_DISPLAY_METERS = True

MACROPAD_BRIGHTNESS = 0.15
MACROPAD_SLEEP_KEYS = 60.0

MACROPAD_DISPLAY_FPS = 30.0

DISPLAY_METER_COUNT = 14
DISPLAY_METER_SPACING = 2

DISPLAY_METER_WIDTH = 10
DISPLAY_METER_HEIGHT = 40

KEYS = [k for k in range(0,12)]
ENCODER_ID= 12
ENCODER_CLICK_ID = 13

METERS = [m for m in range(20,34)]